name: publish on github

on:
    push:
        branches:
            - master

jobs:
    publish-gpr:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 18
                  registry-url: https://npm.pkg.github.com/
                  scope: "@mdalamin3091"
            - run: npm install
            - run: npm run test
            - run: npm run build
            - name: Get short commit hash
              id: commit_hash
              run: echo "::set-output name=hash::$(echo ${GITHUB_SHA::8})"
            - name: Set package version
              run: npm version ${{ steps.commit_hash.outputs.hash }}
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
